### ISSUE TITLE
Is there support for `or` operator?

### ISSUE THREAD

**Issue by nlhuykhang** [tomkallen/datafield#3]
I can see from the API list that `and` is supported by default. How about `or`?

**Comment by tomkallen** [comment]
@nlhuykhang A very good question. Not yet, but it is planned for the next update, so — it's going to be here in a matter of days.

**Comment by tomkallen** [comment]
Resolved in [0.2.0](https://github.com/tomkallen/datafield/releases/tag/v0.2.0)
